name: Update all Node.js Modules

on:
  schedule:
    - cron: "*/5 * * * *"
  
jobs:
 update_node_modules:
    runs-on: windows-latest
    steps:   
     - uses: actions/checkout@v2
     - name: Create report file
       run: date +%s > report.txt
       
     - name: Update all Node Modules
       run: | 
          npm install -g npm-check-updates
          ncu -u
          npm install
          npm install path
          
       
     - name: Commit report
       run: |
          git config --global user.name '${{ secrets.git_username }}'
          git config --global user.email '${{ secrets.git_email }}'
          git add -A
          git commit -am "Updated all NodeJS Modules"
          git push origin ${{ github.GITHUB_REF_NAME }}
